DELETE http://localhost:3001/api/blogs/6687c6f597d0be1e0db6cec3 HTTP/1.1
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlNlY29uZCBhY2NvdW50IiwiaWQiOiI2Njg3OWUwYjlmNGU2ZThkYTY2YzkzYjQiLCJpYXQiOjE3MjAxNzM0MTQsImV4cCI6MTcyMDE3NzAxNH0.X3JxQfwxlLW2Oq-IPqgjIbJaLc6C4YumBBdCu7HO7ic
